// Configuration will be auto-generated by deployment script
// This is a placeholder for development

window.APP_CONFIG = {
    API_URL: 'https://api.example.com/dev',
    OWNER: 'default',
    ENVIRONMENT: 'dev'
};

console.log('📝 Config loaded:', window.APP_CONFIG);